angular.module('personalSite').service('blogService', function() {
  var _posts = [
    {
      title: 'Copyright in Sandbox Games',
      date: 'October 26, 2014',
      author: 'Nick Hathaway',
      body: [
        'Who owns the content created by players of sandbox games like Spore, Minecraft, Little Big Planet, and Second Life? According to the End User License Agreements of most of these games, they would have you believe that all content created by users of their software belongs to game developers, not the players who created them. Minecraft’s EULA is more lenient than most, but it still prohibits commercial gain from “anything we have made unless specifically agreed by us, either in our brand and asset usage guidelines or under this EULA.” After making an exception for fair use, they advise players who disagree with their policies to just “not make content available through our game.”',
        'From a legal standpoint, these explicit copyright guidelines make sense for these companies. Otherwise, they would have to worry about lawsuits from other copyright holders who argue that their users’ creations have infringed upon their intellectual property. Marvel v. NCSoft demonstrates the difficulties of running an online sandbox game where players are given the freedom to create their characters’ costumes. When Marvel sued the creators of City of Heroes, they pointed out that the costume creator could be made to create wolverine and superman-like characters, and that NCSoft was liable for contributory copyright infringement. In order to avoid this type of copyright litigation, the companies that make games like Spore and Second Life have decided to retain ownership over their players’ creations and the right to remove their content without permission from the user who created it (this, combined with the DMCA, makes it easier for these companies to remove potentially infringing content after being notified by other copyright holders.)',
        'Sandbox game developers face the same issues as video streaming sites like YouTube and Vimeo. With respect to copyright, they’re at least given the opportunity to take down infringing content before being held liable themselves. But where does this leave the user? For sites like YouTube, you can dispute an erroneous takedown through their website, but video game developers have taken a less nuanced approach to the content created on their platforms. A representative of EA described it like this:',
        'Spore creations are the intellectual property of EA and any use of these creations is at the discretion of EA. But again, I have been informed that you can use them how you want as long as they are not generating revenue for you.',
        'Instead of acting as a platform for the creation and sharing of original works, Spore positions itself as the sole copyright owner of any content created using its software. For a game with a fairly constrained Creature Creator, which allows players to attach and modify different body parts to a blank body, this justification makes some sense. The game developers created the appearance of each body part, the color palette available for creation, and the mechanism by which players can modify each part of the creature’s body. You could say Spore allows for constrained creative activity, maybe even constrained enough to endow EA with full copyright claims over the work created using their Creature Creator software. But what happens when the software is much more flexible, as in City of Heroes or Minecraft? In NCSoft’s motion to dismiss, for example, they defended their Creation Engine as “a high-tech version of a box of crayons or a set of building blocks, from which players can turn their ideas into (virtual) reality.”',
        'There’s obviously a range of flexibility found in the tools used in sandbox video games. In Minecraft, players are given basic buildings blocks of a world which they use to create models of the Mines of Moria from Lord of the Rings, pixel art of Skyrim characters, and even working computers with RAM. Given a more granular method of creation, players have demonstrated an incredible level of creativity in the things they can create using Minecraft software. The significant differences between creation software in Spore and Minecraft highlights another question relevant to copyright claims in sandbox games: How much freedom must a game’s creator allow before its users can claim to have made original creations. And if users can claim to have made original creations, then wouldn’t the stringent copyright policies in these EULA’s inhibit the creativity that is at the heart of copyright law (i.e. “the Progress of Science and the Useful arts?”)',
        'Then there’s the “generating revenue” clause. Both Spore and Minecraft’s EULA’s prohibit using in-game creations for commercial gain.  These policies become even more confusing when they relate to real-world derivative products. For example, let’s say I use Spore’s Creature Creator to create a unique creature, then I decide to make a mostly accurate drawing of it and sell that drawing online. If the creature was protected by EA’s copyright and if my work wasn’t transformative fair use, then  I have just created a derivative work of the creature, which is the sole right of that creature’s copyright holder, EA Games. If I sell it, then I’m also breaking another section of their EULA, which prohibits me from profiting off of any of my creations in Spore. As an avid fan of Spore, my creativity and desire to re-imagine my character in different mediums has been stunted by EA’s strict approach to copyright.',
        'When I was at a hackerspace in Boston, I met someone who would take sections of his customers’ Minecraft maps and use his 3D printer to make models of their creations. He even used paint to make the textures of his blocks accurate in almost every detail to the video game version. In other words, he creates derivative works of Minecraft creations not protected under any fair use exceptions.  Without the protection of copyright, neither he nor the customer who requested his services could create models of their in-game creations. I believe this is the biggest intellectual property problem facing sandbox games today.',
        'Original content is the driving force behind the success of any sandbox creation game. An active community of creators draws players in and contributes greatly to its replay value, which encourages the widespread sharing and content creation that is central to their business model.  It seems that more freedom to control and create original content both on these platforms and outside of them would only strengthen the community of any sandbox game. Instead, their EULA’s have been influenced by the threat of third-party lawsuits rather than the desire to protect the rights to creativity of their fan base.'
      ],
    },
    {
      title: 'Lawrence Lessig\'s “Latent Ambiguities” the 4th Amendment',
      date: 'January 30, 2015',
      author: 'Nick Hathaway',
      body: [
        'In Larry Lessig’s book Code v2.0, he writes about the “latent ambiguities” that arise when we try to interpret the Constitution in a new technological climate. One of my favorite examples he uses is about a computer worm that “propagates itself on the Net, finding hard disks wherever it can.” This worm, developed hypothetically by the FBI, would search each hard drive for a leaked government document, ignoring all other files, before reporting back whether or not the search was successful. Because this type of search is unburdensome, Lessig argues that its implications exceed the scope of the amendment when it was first written (and for most of the 20th century before the 4th amendment became disentangled from common law ideas on trespass.)',
        'In the context of this week’s readings, I want to extend Lessig’s argument to ideas about privacy, community norms, and the important distinction between police and general public use of technology.  I also want to see if these guiding principles apply equally well to other new and unforeseen technologies, such as DNA sampling. To start, a worm like the one described above would be considered constitutional by Justice Harlan if a). the person who is being searched “has a constitutionally protected reasonable expectation of privacy”, b). “electronic intrusions” are as much an infringement on their 4th amendment rights as physical ones, and c). “that the invasion of a constitutionally protected area by federal authorities is… presumptively unreasonable in the absence of a search warrant.” The first two seem clear. If you store files on a computer, even illegal government documents, you can expect them to be private. However, things get complicated when you start to question how “unreasonable” this type of search would be without a warrant.',
        'No files on the users’ computers are damaged, and the only information that is returned is a simple YES/NO on whether or not someone’s hard drive contains an illegal document. The most difficult aspect of this problem relates to “breaches of privacy” and the conversation we had in class about a loss of private data that results in nothing (i.e., an insurance company loses a plane of your confidential documents, but they all fall directly into a volcano). At first glance, this would make the worm seem constitutional. In a way, there is no privacy breach, because the worm is “blind” to everything but the illegal government document question. But if the fourth amendment protects you against a warrantless search when you store marijuana in your house, then why wouldn’t it protect you against the worm, even if you had a copy of the illegal document on your computer?',
        'The worm solution is tempting because it’s practical. But much like YouTube’s algorithms for identifying copyright infringing content, it can also be overbroad and, in some cases, unconstitutional.  What fascinates me most about 4th amendment debates is the societal component (i.e. “is this person’s expectation of privacy reasonable?”) Given the diverging opinions of the justices, and of many lower circuit courts, it seems that there is no straightforward answer to what constitutes a reasonable expectation of privacy or “the legitimate needs of law enforcement.” In Katz v. U.S., the judges describe how warrants are essentially judicial buffers between the police and those being searched. But what if the police aren’t the ones actually doing the searching? In the future, we might become more comfortable with computers “seeing” for us, even to the point when we no longer consider programming-based solutions to be a breach of privacy. In that world, a narrowly defined worm might become constitutional.',
        'Larry Lessig’s “latent ambiguities” apply equally well to the constitutional status of our garbage, especially when you consider the increasing sophistication of DNA sampling. In California v. Greenwood, the court decided that there is no reasonable expectation of privacy when it comes to what we throw away. Maybe the trash contains personally identifying information, but when you just leave it in the streets, where anyone can access it, then there’s no way it’s going to be covered by the 4th amendment against a warrantless search. Then, something like this happens:',
        'In 2004, police in Onondaga County, NY, used saliva from Donald Sigsbee’s discarded soda straw to connect him to a murder. The officers retrieved the straw from a trashcan at Wendy’s and successfully used it as evidence that led to a 25-year conviction.',
        'The context of California v. Greenwood resulted in a seemingly fair decision which seems strangely dystopian only twenty-four years later. In Justice Brennan’s dissent, the “private lives… concealed safely in a trash bag” probably didn’t take into account the possibility of DNA evidence. The idea that police can rummage through someone’s discarded trash and use it in a criminal investigation seems ridiculous. Even the central argument of California v. Greenwood, that even “snoopers” could go through your trash, starts to seem weak when the police are finding evidence “in plain public view” using equipment that’s clearly not available to the general public. Are we supposed to walk around with our own trash bags, making sure to collect every loose hair and patch of skin cells that fall off us during our daily routines? Isn’t there some consideration – not even of a reasonable expectation of privacy – but of the practical limits on one’s ability to keep their personal effects private in the first place?'
      ]
    }
  ]

  this.getPosts = function() {
    return _posts;
  }
})